services:
  redmine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: ${VARIANT:-trixie}
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_ADAPTER: mysql2
      DB_NAME: redmine
      DB_HOST: db
      DB_USER: redmine
      DB_PASSWORD: redmine
      REDMINE_LANG: ja
      # REDMINE_ADMIN_PASSWORD: your_secure_password
      REDMINE_REST_API_ENABLED: "true"  # Set to "true" to enable REST API
      REDMINE_DEFAULT_PROJECTS_PUBLIC: "0"  # Set to "1" for public, "0" for private
    volumes:
      - ..:/workspace:cached
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      TZ: Asia/Tokyo
volumes:
  db-data: