version: '3.8'

services:
  redmine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: ${VARIANT:-trixie}
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_ADAPTER: mysql2
      DB_NAME: redmine
      DB_HOST: db
      DB_USER: redmine
      DB_PASSWORD: redmine
      # REDMINE_ADMIN_PASSWORD: your_secure_password
      # REDMINE_RESET_ON_START: "true"  # Set to "true" to reset environment on next start
    volumes:
      - ..:/workspace:cached
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db-data: